.\" ##########################################################################
.\" #                      __                                                #
.\" #      ________ ___   / /  ___     Scala 2 On-line Manual Pages          #
.\" #     / __/ __// _ | / /  / _ |    (c) 2002-2010, LAMP/EPFL              #
.\" #   __\ \/ /__/ __ |/ /__/ __ |                                          #
.\" #  /____/\___/_/ |_/____/_/ | |    http://scala-lang.org/                #
.\" #                           |/                                           #
.\" ##########################################################################
.\"
.\" Process this file with nroff -man scala.1
.\"
.TH sbaz 1  "May 9, 2006" "version 0.1" "USER COMMANDS"
.\"
.\" ################################# NAME ###################################
.\"
.SH NAME
sbaz \- Scala Bazaars package distribution system
.\"
.\" ############################### SYNOPSIS #################################
.\"
.SH SYNOPSIS
\fBsbaz\fR [ <\fIarguments\fR> ]
.\"
.\" ############################## DESCRIPTION ###############################
.\"
.SH DESCRIPTION
Scala Bazaars allows users to manage packages in various ways.
Locally, packages can be installed an uninstalled.  Over the network,
packages may be exchanged via \fIbazaars\fR.
.PP
The command-line arguments are documented internally.  Run "sbaz help"
to get an overview, or "sbaz help \fIcommand\fR" to get information
about a particular command.

.\"
.\" ############################## AUTHOR(S) #################################
.\"
.SH AUTHOR
Written by Lex Spoon <lex@debian.org>.
.\"
.\" ################################ BUGS ####################################
.\"
.SH "REPORTING BUGS"
Report bugs to <scala@listes.epfl.ch>.
.\"
.\" ############################# COPYRIGHT ##################################
.\"
.SH COPYRIGHT
Copyright \(co 2002-2010 LAMP/EPFL
.PP
This is free software; see the distribution for copying conditions.  There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" ############################### SEE ALSO #################################
.\"
.SH "SEE ALSO"
.BR sbaz-setup(1)
.BR scala(1)
.BR scalac(1)
.\" .BR scaladoc(1),
.\" .BR scalaint(1)
.\"
.\" ##########################################################################
