#!/bin/bash -ex
# need to re-declare it as an array, not sure how to do that directly in jenkins
declare -a sshCharaArgs="$sshCharaArgs"

url="http://downloads.typesafe.com/scala/$version"

if [[ "$version" =~ .*-nightly ]]
then archivesDir="~linuxsoft/archives/scala/nightly/2.11.x"
else archivesDir="~linuxsoft/archives/scala"
fi

# make this build restartable (if interrupted, partial files may remain, and resuming isn't very reliable)
[[ -n $version ]] && ssh "${sshCharaArgs[@]}" "rm -f $archivesDir/scala-*$version* && rm -rf $archivesDir/api/$version/ ||:"

cacheBuster="$(date +%s | tail -c2 | head -c1)"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-$version.msi       '$url/scala.msi?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-$version.zip       '$url/scala-$version.zip?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-$version.tgz       '$url/scala-$version.tgz?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-$version.deb       '$url/scala-$version.deb?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-$version.rpm       '$url/scala-$version.rpm?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-docs-$version.zip  '$url/scala-docs-$version.zip?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-docs-$version.tgz  '$url/scala-docs-$version.tgz?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-docs-$version.txz  '$url/scala-docs-$version.txz?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-tool-support-$version.zip '$url/scala-tool-support-$version.zip?$cacheBuster'"
ssh "${sshCharaArgs[@]}" "cd $archivesDir && wget -nv -O scala-tool-support-$version.tgz '$url/scala-tool-support-$version.tgz?$cacheBuster'"

echo "Expanding scala-library API docs for $version to api/$version (with subdirectories for scala-compiler and scala-reflect)."
ssh "${sshCharaArgs[@]}" "cd $archivesDir && mkdir -p api/$version && tar -xvz --strip-component 1 -f scala-docs-$version.tgz -C api/$version" # tar on jenkins does not support the -s option
