#!/bin/bash -ex

url="https://downloads.lightbend.com/scala/$version"

if [[ "$version" =~ ^.*-(bin|pre)-[0-9a-f]+$ ]]
then archivesDir="~linuxsoft/archives/scala/nightly/2.13.x"
else archivesDir="~linuxsoft/archives/scala"
fi

# make this build restartable (if interrupted, partial files may remain, and resuming isn't very reliable)
[[ -n $version ]] && ssh chara "rm -f $archivesDir/scala-*$version* && rm -rf $archivesDir/api/$version/ ||:"

cacheBuster="$(date +%s | tail -c2 | head -c1)"
ssh chara "cd $archivesDir && wget -nv -O scala-$version.msi       '$url/scala-$version.msi?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-$version.zip       '$url/scala-$version.zip?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-$version.tgz       '$url/scala-$version.tgz?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-$version.deb       '$url/scala-$version.deb?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-$version.rpm       '$url/scala-$version.rpm?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-docs-$version.zip  '$url/scala-docs-$version.zip?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-docs-$version.tgz  '$url/scala-docs-$version.tgz?$cacheBuster'"
ssh chara "cd $archivesDir && wget -nv -O scala-docs-$version.txz  '$url/scala-docs-$version.txz?$cacheBuster'"

echo "Expanding scala-library API docs for $version to api/$version (with subdirectories for scala-compiler and scala-reflect)."
ssh chara "cd $archivesDir && mkdir -p api/$version && tar -xvz --strip-component 2 -f scala-docs-$version.tgz -C api/$version && mv api/$version/scala-library/* api/$version/" # tar on jenkins does not support the -s option
