#!/bin/bash -ex
# need to re-declare it as an array, not sure how to do that directly in jenkins
declare -a sshCharaArgs="$sshCharaArgs"

if [[ "$version" =~ .*-nightly ]]
then archivesDir="~linuxsoft/archives/scala/nightly/2.12.x"
else archivesDir="~linuxsoft/archives/scala"
fi

echo "Symlinking $archivesDir/api/$version to $archivesDir/api/2.12.x."

ssh "${sshCharaArgs[@]}" "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn $version 2.12.x"

# needs to run once on new major release:
# ssh "${sshCharaArgs[@]}" "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn 2.12.x current"

