#!/bin/bash -ex

if [[ "$version" =~ ^.*-(bin|pre)-[0-9a-f]+$ ]]
then archivesDir="~linuxsoft/archives/scala/nightly/2.13.x"
else archivesDir="~linuxsoft/archives/scala"
fi

echo "Symlinking $archivesDir/api/$version to $archivesDir/api/2.13.x."

ssh chara "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn $version 2.13.x"

# needs to run once on new major release:
# ssh chara "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn 2.13.x current"
